<a href="https://www.kaggle.com/code/iqbalhossain25/feature-engineering-ordinal-encoding?scriptVersionId=232339431" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/customer-csv/customer.csv


# This line use for read Data (csv_file)

In [2]:
df= pd.read_csv('/kaggle/input/customer-csv/customer.csv')
df.head(10)

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No
5   31  Female  Average    School       Yes
6   18    Male     Good    School        No
7   60  Female     Poor    School       Yes
8   65  Female  Average        UG        No
9   74    Male     Good        UG       Yes

# This line use for type of datatype

In [3]:
df.dtypes

age           int64
gender       object
review       object
education    object
purchased    object
dtype: object

Insial goal applying ordinal encoding in review and education 

# This line use for remove unnecessary column

In [4]:
df=df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# Always remember  before train the data please do train_test_split 

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [6]:
X_train

review education
8   Average        UG
10     Good        UG
5   Average    School
35     Poor    School
9      Good        UG
15     Poor        UG
3      Good        PG
20  Average    School
28     Poor    School
31     Poor    School
13  Average    School
34  Average    School
25     Good    School
41     Good        PG
23     Good    School
36     Good        UG
1      Poor        UG
2      Good        PG
24  Average        PG
14     Poor        PG
47     Good        PG
16     Poor        UG
40     Good    School
42     Good        PG
21  Average        PG
38     Good    School
43     Poor        PG
49     Good        UG
18     Good    School
6      Good    School
32  Average        UG
11     Good        UG
33     Good        PG
37  Average        PG
27     Poor        PG
19     Poor        PG
44  Average        UG
22     Poor        PG
48     Good        UG
30  Average        UG

# Tranformer of OrdinalEncoding 

In [7]:
from sklearn.preprocessing import OrdinalEncoder


if we didn't use manually categories its generate value randomly 

In [8]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

# On this line of  code transform categorical value to numerical

In [9]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [10]:
X_train

array([[1., 1.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [1., 1.]])

In [11]:
X_test

array([[0., 2.],
       [0., 0.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [1., 1.]])

#  remember !! lableEncoding always use output or target varibale

In [12]:
from sklearn.preprocessing import LabelEncoder


In [13]:
le=LabelEncoder()

In [14]:
le.fit(y_train)

LabelEncoder()

# You don't  need to manual set it generate automatically 

In [15]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [16]:
y_train= le.transform(y_train)
y_test= le.transform(y_test)

In [17]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0])

# Just a example of own  function ordinal_encoding

In [18]:
def ordinal_encode(data, category_order):
    """
    Encodes categorical data using ordinal encoding.

    Parameters:
    data (list): The input data to encode.
    category_order (list): Specifies the order of categories.

    Returns:
    encoded_data (list): Ordinally encoded data.
    """
    encoded_data = []
    for value in data:
        encoded_data.append(category_order.index(value))
    return encoded_data

# Example usage
data = ["low", "medium", "high", "medium"]
category_order = ["low", "medium", "high"]  # Specify category order

encoded_data = ordinal_encode(data, category_order)
print("Ordinally Encoded Data:")
print(encoded_data)


Ordinally Encoded Data:
[0, 1, 2, 1]
