<a href="https://www.kaggle.com/code/iqbalhossain25/feature-engineering-column-transform?scriptVersionId=233581660" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/cobit-toydata/covid_toy.csv


In [2]:
df=pd.read_csv('/kaggle/input/cobit-toydata/covid_toy.csv')
df.head(5)

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [3]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [5]:
X_train

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


age  gender  fever   cough       city
24   13  Female  100.0  Strong    Kolkata
50   19    Male  101.0    Mild      Delhi
17   40  Female   98.0  Strong      Delhi
19   42  Female    NaN  Strong  Bangalore
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
76   80    Male  100.0    Mild  Bangalore
72   83  Female  101.0    Mild    Kolkata
63   10    Male  100.0    Mild  Bangalore
69   73  Female  103.0    Mild      Delhi
95   12  Female  104.0    Mild  Bangalore

[80 rows x 5 columns]

In [6]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()

X_train_age=ss.fit(X_train[['age']])
X_train_age=ss.transform(X_train[['age']])

X_test_age=ss.fit(X_test[['age']])
X_test_age=ss.transform(X_test[['age']])

In [7]:
X_train_age

array([[-1.29256235],
       [-1.0540272 ],
       [-0.21915417],
       [-0.13964245],
       [ 0.77474229],
       [-0.45768932],
       [ 0.575963  ],
       [-0.85524791],
       [ 1.45059189],
       [ 0.93376573],
       [ 0.81449815],
       [ 0.93376573],
       [-1.0540272 ],
       [-1.57085336],
       [ 0.89400987],
       [-0.45768932],
       [ 1.17230088],
       [ 0.73498643],
       [ 1.49034775],
       [ 1.45059189],
       [ 0.41693957],
       [-0.93475962],
       [ 0.21816027],
       [-1.61060922],
       [-0.29866589],
       [ 1.41083603],
       [-1.0540272 ],
       [-0.13964245],
       [-1.09378306],
       [ 0.05913684],
       [ 0.01938098],
       [ 0.575963  ],
       [ 0.77474229],
       [ 0.53620714],
       [-1.37207407],
       [-0.77573619],
       [-0.13964245],
       [ 1.33132431],
       [ 0.05913684],
       [-0.29866589],
       [-1.0540272 ],
       [ 0.21816027],
       [ 0.13864856],
       [ 0.17840442],
       [-0.5769569 ],
       [-0

# This portion of code use for remove numerical null value replacing with mean

**First try with out using Column Transformation**

In [8]:
from sklearn.impute import SimpleImputer
si=SimpleImputer()

X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])

In [9]:
X_train_fever

array([[100.        ],
       [101.        ],
       [ 98.        ],
       [100.77464789],
       [101.        ],
       [ 98.        ],
       [ 99.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [ 99.        ],
       [103.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [101.        ],
       [104.        ],
       [102.        ],
       [ 98.        ],
       [102.        ],
       [104.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [100.77464789],
       [101.        ],
       [100.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [103.        ],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [ 98.        ],
       [104.        ],
       [100.77464789],
       [100.        ],
       [101.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [103

In [10]:
# applying Ordinal Encoding 
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Mild','Strong']])

X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

In [11]:
X_train_cough

array([[1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],

In [12]:
# one hot encoding in city and gender

from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False)

X_train_city_gender=ohe.fit_transform(X_train[['gender','city']])
X_test_city_gender=ohe.fit_transform(X_test[['gender','city']])

X_train_city_gender.shape

(80, 4)

In [13]:
X_train_city_gender

array([[0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],


In [14]:

X_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_cough,X_train_city_gender),axis=1)

X_test_transformed=np.concatenate((X_test_age,X_test_fever,X_test_cough,X_test_city_gender),axis=1)

X_train_transformed.shape

(80, 7)

In [15]:
X_train_transformed

array([[-1.29256235e+00,  1.00000000e+02,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [-1.05402720e+00,  1.01000000e+02,  0.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-2.19154170e-01,  9.80000000e+01,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.39642453e-01,  1.00774648e+02,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 7.74742293e-01,  1.01000000e+02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00],
       [-4.57689321e-01,  9.80000000e+01,  1.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [ 5.75963000e-01,  9.90000000e+01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.0000000

# Now Applying Column Transformation Just do this thing In SingleLine

In [16]:
from sklearn.compose import ColumnTransformer

In [17]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', StandardScaler(), ['age']),
    ('tnf2', SimpleImputer(), ['fever']),
    ('tnf3', OrdinalEncoder(), ['cough']),
    ('tnf4', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
], remainder='passthrough')


In [18]:
transformer.fit_transform(X_train)

array([[-1.29256235e+00,  1.00000000e+02,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [-1.05402720e+00,  1.01000000e+02,  0.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-2.19154170e-01,  9.80000000e+01,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.39642453e-01,  1.00774648e+02,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 7.74742293e-01,  1.01000000e+02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00],
       [-4.57689321e-01,  9.80000000e+01,  1.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [ 5.75963000e-01,  9.90000000e+01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.0000000

In [19]:
transformer.fit_transform(X_train).shape

(80, 7)

# Another Approach # 

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1', StandardScaler(), ['age']),
    ('tnf2', SimpleImputer(strategy='mean'), ['fever']),
    ('tnf3', Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OrdinalEncoder())
    ]), ['cough']),
    ('tnf4', Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(sparse_output=False, drop='first'))
    ]), ['gender', 'city'])
], remainder='passthrough')


In [21]:
transformer.fit_transform(X_train)

array([[-1.29256235e+00,  1.00000000e+02,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [-1.05402720e+00,  1.01000000e+02,  0.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-2.19154170e-01,  9.80000000e+01,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.39642453e-01,  1.00774648e+02,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 7.74742293e-01,  1.01000000e+02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00],
       [-4.57689321e-01,  9.80000000e+01,  1.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [ 5.75963000e-01,  9.90000000e+01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.0000000